#server:
#  port: 58081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mnu # studs
    username: mnu # s244077
    password: mnu
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.yandex.com
    username: mnu.sem@yandex.ru
    password: wlacmxzcyoszwnmr
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: mnu.config.DbDialect