spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mnu
    username: mnu
    password: mnu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: false
      properties:
        hibernate:
          dialect: mnu.config.DbDialect